### ISSUE TITLE
Script just never converts, creates a 0KB file

### ISSUE THREAD

**Issue by DanSolomon** [TheCaptain989/lidarr-flac2mp3#31]
Hi, getting an issue with this where after enabling and running, it creates a 0KB file for the first item it tries to convert and then just stops. Used debug-2 as the script and got this result (can provide more if needed):

`22-6-20 00:57:31.1|[442]Info|Lidarr event: AlbumDownload, Artist: Beck (12), Album: Beck (2757), Export bitrate: 320k, Track(s): /music/Beck/Beck (2000)/01 - Arabian Nights.flac|/music/Beck/Beck (2000)/02 - Dirty Dirty.flac|/music/Beck/Beck (2000)/03 - Midnite Vultures.flac|/music/Beck/Beck (2000)/04 - Mixed Bizness (The Latin Mix by Scatter-Shot Theory).flac|/music/Beck/Beck (2000)/05 - Mixed Bizness (Hardmixn by Jake Kozel, aka Socket 7).flac|/music/Beck/Beck (2000)/06 - Salt in the Wound.flac|/music/Beck/Beck (2000)/07 - Sexx Laws (Malibu remix).flac|/music/Beck/Beck (2000)/08 - Zatyricon.flac
22-6-20 00:57:31.1|[442]Debug|Using constant bitrate of 320k
22-6-20 00:57:31.1|[442]Info|Writing: /music/Beck/Beck (2000)/01 - Arabian Nights.mp3
22-6-20 00:57:31.1|[442]Debug|Executing: nice /usr/bin/ffmpeg -loglevel error -i "/music/Beck/Beck (2000)/01 - Arabian Nights.flac" -c:v copy -map 0 -y -acodec libmp3lame -b:a 320k -write_id3v1 1 -id3v2_version 3 "/music/Beck/Beck (2000)/01 - Arabian Nights.mp3"
22-6-20 00:57:31.5|[442]
22-6-20 00:57:31.5|[442]Enter command: <target>|all <time>|-1 <command>[ <argument>]`

**Comment by TheCaptain989** [comment]
Hmmm.  I don't see an obvious issue from the output.  Could you try running the script with a `--debug 2` option and posting the output here?

**Comment by janaxhell** [comment]
Hi, not the OP, but I am having the same issue, suddenly FLAC albums are no compressed to MP3. flac2mp3 dies soon after starting. All my *arrs have a warning stating "This image is now based on Alpine."  I have tried to connect to debug-2 script, but all I see in Lidarr log is:

2022-06-22T11:36:51.406462546Z [Info] IdentificationService: Identifying album 1/1 
2022-06-22T11:36:51.441656834Z [Info] ImportApprovedTracks: Importing album 1/1 
2022-06-22T11:36:51.453469588Z [Info] ImportApprovedTracks: Importing 22 tracks 
2022-06-22T11:36:53.630698221Z [Error] flac2mp3-debug-2.sh: Debug|Enabling debug logging level 2. Starting AlbumDownload run. 

and nothing else happens, it just sits there, with track 1 half-baked to MP3 and the rest still in FLAC.

**Comment by janaxhell** [comment]
Ok, here it's the log of what happened when I wrote the previous message https://pastebin.com/98BJSR0v 
I have now set flac2mp3 to 1.3, but it still doesn't work: 
`2022-06-22T22:01:13.365178059Z [Info] TrackGroupingService: Grouping 22 tracks 
2022-06-22T22:01:13.374331312Z [Info] IdentificationService: Identifying album 1/1 
2022-06-22T22:01:13.578976291Z [Info] ImportApprovedTracks: Importing album 1/1 
2022-06-22T22:01:13.720034376Z [Info] ImportApprovedTracks: Importing 22 tracks 
2022-06-22T22:01:16.342214277Z [Warn] NotificationService: Unable to send OnReleaseImport notification to: FLAC to MP3 
2022-06-22T22:01:16.342232509Z 
2022-06-22T22:01:16.342238962Z [v1.0.2.2592] System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/usr/local/bin/flac2mp3-debug-2.sh' with working directory '/app/lidarr/bin'. No such file or directory
2022-06-22T22:01:16.342243610Z    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
2022-06-22T22:01:16.342248318Z    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
2022-06-22T22:01:16.342250730Z    at System.Diagnostics.Process.Start()
2022-06-22T22:01:16.342261501Z    at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 185
2022-06-22T22:01:16.342264730Z    at NzbDrone.Common.Processes.ProcessProvider.StartAndCapture(String path, String args, StringDictionary environmentVariables) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 216
2022-06-22T22:01:16.342267411Z    at NzbDrone.Core.Notifications.CustomScript.CustomScript.ExecuteScript(StringDictionary environmentVariables) in D:\a\1\s\src\NzbDrone.Core\Notifications\CustomScript\CustomScript.cs:line 218
2022-06-22T22:01:16.342271062Z    at NzbDrone.Core.Notifications.CustomScript.CustomScript.OnReleaseImport(AlbumDownloadMessage message) in D:\a\1\s\src\NzbDrone.Core\Notifications\CustomScript\CustomScript.cs:line 96
2022-06-22T22:01:16.342275489Z    at NzbDrone.Core.Notifications.NotificationService.Handle(AlbumImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\Notifications\NotificationService.cs:line 174
2022-06-22T22:01:16.342279527Z 
2022-06-22T22:01:16.342281737Z 
2022-06-22T22:01:17.074980291Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.094002532Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.108038991Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.116824615Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.124086848Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.129845588Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.135296619Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.140728188Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.146226860Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.151727075Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.157047505Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.162314538Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.167881621Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.173242906Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.178806679Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.184670421Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.190351684Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.195751193Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.201134243Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.206871948Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.212833002Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused 
2022-06-22T22:01:17.218842971Z [Error] post-process-flac-to-mp3.sh: curl: (7) Failed to connect to 172.17.0.1 port 3030 after 0 ms: Connection refused `

According to flac2mp3.0.txt, last time the script worked fine was june, 10th, then it started doing this:

`22-6-16 15:50:03.2|[7455]Info|Lidarr event: AlbumDownload, Artist: Tasmin Archer (2477), Album: Great Expectations (32201), Export bitrate: 320k, Track(s): /music/Pop 1990/Tasmin Archer/Tasmin Archer - 1992 - Great Expectations [FLAC]/01 - Sleeping Satellite.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 1992 - Great Expectations [FLAC]/02 - Arienne.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 1992 - Great Expectations [FLAC]/03 - Lords of the New Church.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 1992 - Great Expectations [FLAC]/04 - When It Comes Down to It.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 1992 - Great Expectations [FLAC]/05 - Steeltown.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 1992 - Great Expectations [FLAC]/06 - The Higher You Climb.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 1992 - Great Expectations [FLAC]/07 - In Your Care.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 1992 - Great Expectations [FLAC]/08 - Somebody's Daughter.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 1992 - Great Expectations [FLAC]/09 - Hero.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 1992 - Great Expectations [FLAC]/10 - Ripped Inside.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 1992 - Great Expectations [FLAC]/11 - Halfway to Heaven.flac
22-6-16 15:50:03.2|[7455]Info|Writing: /music/Pop 1990/Tasmin Archer/Tasmin Archer - 1992 - Great Expectations [FLAC]/01 - Sleeping Satellite.mp3
22-6-16 15:50:06.0|[7455]
22-6-16 15:50:06.0|[7455]Enter command: <target>|all <time>|-1 <command>[ <argument>]
22-6-16 15:54:50.9|[7540]Info|Lidarr event: Test
22-6-16 15:54:50.9|[7540]Info|Script was test executed successfully.
22-6-20 18:56:20.1|[25303]Info|Lidarr event: AlbumDownload, Artist: Alice Merton (559), Album: S.I.D.E.S. (7053), Export bitrate: 320k, Track(s): /music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/01 - Loveback.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/02 - Island.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/03 - Future.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/04 - Same Team.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/05 - Blurry.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/06 - Everything.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/07 - Blindside.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/08 - Shiny Things.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/09 - 100 Stories.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/10 - Hero.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/11 - Mania.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/12 - Vertigo.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/13 - Breathe In, Breathe Out.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/14 - Letting You Know.flac|/music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/15 - The Other Side.flac
22-6-20 18:56:20.1|[25303]Info|Writing: /music/Pop 2010/Alice Merton/Alice Merton - 2022 - S.I.D.E.S. [FLAC]/01 - Loveback.mp3
22-6-20 18:56:22.6|[25303]
22-6-20 18:56:22.6|[25303]Enter command: <target>|all <time>|-1 <command>[ <argument>]
22-6-20 19:48:32.1|[25502]Info|Lidarr event: Test
22-6-20 19:48:32.1|[25502]Info|Script was test executed successfully.
22-6-22 01:02:31.4|[6922]Info|Lidarr event: AlbumDownload, Artist: Tasmin Archer (2477), Album: On (32203), Export bitrate: 320k, Track(s): /music/Pop 1990/Tasmin Archer/Tasmin Archer - 2006 - On [FLAC]/01 - Take Care.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 2006 - On [FLAC]/02 - Sedan.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 2006 - On [FLAC]/03 - Complaints.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 2006 - On [FLAC]/04 - Effect Is Monotony.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 2006 - On [FLAC]/05 - Violence.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 2006 - On [FLAC]/06 - A Day Will Come.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 2006 - On [FLAC]/07 - Emergency.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 2006 - On [FLAC]/08 - A Letter to God.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 2006 - On [FLAC]/09 - Hope.flac|/music/Pop 1990/Tasmin Archer/Tasmin Archer - 2006 - On [FLAC]/10 - Hello.flac
22-6-22 01:02:31.4|[6922]Info|Writing: /music/Pop 1990/Tasmin Archer/Tasmin Archer - 2006 - On [FLAC]/01 - Take Care.mp3
22-6-22 01:02:35.0|[6922]
22-6-22 01:02:35.0|[6922]Enter command: <target>|all <time>|-1 <command>[ <argument>]
22-6-22 01:37:46.9|[7045]Info|Lidarr event: AlbumDownload, Artist: Porridge Radio (2277), Album: Waterslide, Diving Board, Ladder to the Sky (25995), Export bitrate: 320k, Track(s): /music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/01 - .flac|/music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/02 - Back to the Radio.flac|/music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/03 - Trying.flac|/music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/04 - Birthday Party.flac|/music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/05 - End of Last Year.flac|/music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/06 - Rotten.flac|/music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/07 - U Can Be Happy If U Want To.flac|/music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/08 - Flowers.flac|/music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/09 - Jealousy.flac|/music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/10 - I Hope She’s Okay 2.flac|/music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/11 - Splintered.flac|/music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/12 - The Rip.flac|/music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/13 - Waterslide, Diving Board, Ladder to the Sky.flac
22-6-22 01:37:46.9|[7045]Info|Writing: /music/New Wave 2010/Porridge Radio/Porridge Radio - 2022 - Waterslide, Diving Board, Ladder to the Sky [FLAC]/01 - .mp3
22-6-22 01:37:49.2|[7045]
22-6-22 01:37:49.2|[7045]error parsing debug value
22-6-22 01:37:49.2|[7045]debug=0
22-6-22 01:37:49.7|[7045]stream #0:
22-6-22 01:37:49.7|[7045]  keyframe=1
22-6-22 01:37:49.7|[7045]  duration=0.093
22-6-22 01:37:49.7|[7045]  dts=56.564  pts=56.564
22-6-22 01:37:49.7|[7045]  size=7499
22-6-22 01:37:49.7|[7045][mp3 @ 0x7f37c46130c0] Delay between the first packet and last packet in the muxing queue is 10004898 > 10000000: forcing output
22-6-22 01:37:49.7|[7045]    Last message repeated 2 times
22-6-22 01:37:49.7|[7045]stream #0:
22-6-22 01:37:49.7|[7045]  keyframe=1
22-6-22 01:37:49.7|[7045]  duration=0.093
22-6-22 01:37:49.7|[7045]  dts=56.657  pts=56.657
22-6-22 01:37:49.7|[7045]  size=7424
22-6-22 01:37:49.8|[7045][mp3 @ 0x7f37c46130c0] Delay between the first packet and last packet in the muxing queue is 10004898 > 10000000: forcing output
22-6-22 01:37:49.8|[7045]    Last message repeated 3 times
22-6-22 01:37:49.8|[7045]stream #0:
22-6-22 01:37:49.8|[7045]  keyframe=1
22-6-22 01:37:49.8|[7045]  duration=0.093
22-6-22 01:37:49.8|[7045]  dts=56.750  pts=56.750
22-6-22 01:37:49.8|[7045]  size=7369
22-6-22 01:37:49.8|[7045][mp3 @ 0x7f37c46130c0] Delay between the first packet and last packet in the muxing queue is 10004898 > 10000000: forcing output
22-6-22 01:37:49.8|[7045]    Last message repeated 2 times
22-6-22 01:37:49.8|[7045]stream #0:
22-6-22 01:37:49.8|[7045]  keyframe=1
22-6-22 01:37:49.8|[7045]  duration=0.093
22-6-22 01:37:49.8|[7045]  dts=56.842  pts=56.842
22-6-22 01:37:49.8|[7045]  size=7544`

which looks like it reads all the FLAC tracks, then starts writing the first MP3 track, but moves to next album before even finishig it.

**Comment by TheCaptain989** [comment]
Thank you.  Hmmmm.
I had a quick chance to look things over on my rig.  The last time the script ran for me was 6/15 and it ran fine.  However, I have tried it again and was able to reproduce the `Enter command: <target>` message text, though the file seems like it started to convert just fine (e.g., it wasn't 0 bytes), but it hangs for some reason.

I do think something with the latest Lidarr container messed something up, but I don't know what it is right off.  Maybe an ffmpeg compile difference?  Ugh.

Sorry, I'm out of time today!

**Comment by janaxhell** [comment]
Don't worry and thanks for checking. I'll manage manually until a solution is found, I don't download that many albums. I have Watchtower updating containers, I don't want to fight with it.

**Comment by TheCaptain989** [comment]
Okay, so I lied.  I couldn't stay away! 😄

I figured it out, though it makes me question how it was working before.  It turns out that ffmpeg is by default in interactive mode.  There's a simple switch to turn this off. (see [ffmpeg options](https://ffmpeg.org/ffmpeg.html#Main-options)).

About to upload a new build.

P.S. - Special thanks to [Igor Kromin](https://www.igorkromin.net/index.php/2016/12/23/prevent-errors-during-ffmpeg-execution-in-a-loop/)'s blog for helping me figure it out!

**Comment by TheCaptain989** [comment]
It's in the script.  I also fixed an API issue that I noticed cropped up.  If you set `DOCKER_MODS=thecaptain989/lidarr-flac2mp3:latest` you'll get the fix.  I'm working on a pull request for docker-mods now.
